[tool.poetry]
name = "basecampapi"
version = "0.2.4"
description = ""
authors = ["mare011rs <mare011rs@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7"
requests = "*"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
